### ISSUE TITLE
Where is the search code?

### ISSUE THREAD

**Issue by iFLYTEK-Embodied-Robotics-Team** [xieydd/Pytorch-Single-Path-One-Shot-NAS#2]

**Comment by iFLYTEK-Embodied-Robotics-Team** [comment]
@xieydd Hi, author, Thank you for your great share, Could you provide the search code?

**Comment by xieydd** [comment]
@zhangyuan1994511 , in `model/network.py` and `model/blocks.py`, you can find the main process of search. It is not recommended to use this repo,  [mxnet version](https://github.com/CanyonWind/Single-Path-One-Shot-NAS-MXNet) is better.
